before_script:
  - docker info

stages:
  - build
  - push
  - deploy

build_job:
  stage: build
  tags:
    - portfolio-runner
  script:
    - docker image build -t portfolio .

push_job:
  stage: push
  tags:
    - portfolio-runner
  script:
    - gcloud auth configure-docker
    - docker image tag portfolio eu.gcr.io/portfolio/portfolio
    - docker image push eu.gcr.io/portfolio/portfolio
    
deploy_job:
  stage: deploy
  tags:
    - portfolio-runner
  script:
    - cd ansible
    - ansible-playbook -i main.yml
