before_script:
  - docker info

stages:
  - build
  - push
  - deploy

build_job:
  stage: build
  tags:
    - portfolio-runner
  script:
    - docker image build -t portfolio .
    
deploy_job:
  stage: deploy
  tags:
    - portfolio-runner
  script:
    - cd ansible
    - ansible-playbook -i inventory main.yml -vvvv
