- name: Run Portfolio container
  become: true
  hosts: localhost
  roles:
    - gcr-authenticate
  tasks:
    - name: Start Portfolio
      service:
        name: portfolio
        image: portfolio
        state: started
        ports:
          - "80:3000"





   


