- name: Portfolio container
  hosts: frontend
  become: true
  tasks:
    - name: Start Portfolio
      service:
        name: portfolio
        ports:
          - "80:3000"
        state: started




   


