- name: Configure portfolio
  become: true
  roles:
    - docker
    - gcr-authenticate
  tasks:
    - name: Create portfolio container
      docker_container:
        name: portfolio
        image: eu.gcr.io/portfolio/portfolio:latest
        ports:
          - "3000:3000"

