             
# start portfolio container
- name: Portfolio container
  become: true
  hosts: frontend
  tasks:
    - name: Run Portfolio
      docker_container:
        name: portfolio
        image: portfolio
        ports:
          - "80:3000"




   


