- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_id: portfolio
    machine_type: e2-small
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    zone: europe-north1-a
    compute_engine_default_service_account: 1032823057839-compute@developer.gserviceaccount.com
  tasks:
    - name: Launch instances
      gcp_compute_instance:
        auth_kind: serviceaccount
        name: portfolio
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ image }}"
        network_interfaces:
          - access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
        project: "{{ project_id }}"
        zone: "{{ zone }}"
        service_accounts:
          - email: "{{ compute_engine_default_service_account }}"
            scopes:
              - https://www.googleapis.com/auth/devstorage.read_only
        tags:
          items:
            - http-server
            - https-server

- name: Configure portfolio
  become: true
  roles:
    - docker
    - gcr-authenticate
  tasks:
    - name: Create portfolio container
      docker_container:
        name: portfolio
        image: eu.gcr.io/portfolio/portfolio:latest
        ports:
          - "3000:3000"

